language: php

php:
  - 7.3

services:
  - mysql

before_script:
  - cp .env.travis .env
  - sudo mysql -e 'CREATE DATABASE testing;'
  - php artisan migrate --no-interaction -vvv
  - composer self-update
  - composer install --no-interaction


script:
  - php artisan key:generate
  - vendor/bin/phpunit